apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodeapp-deploy1
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nodeapp
            component: nodeapp1
    template:
        metadata:
            labels:
                app: nodeapp
                component: nodeapp1
        spec:
            containers:
            - name: nodeapp2
              image: kangjuseong/nodeapp-git:1.3.0
              ports:
              - containerPort: 8080