apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodeapp-deploy
    namespace: test1
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nodeapp1
    template:
        metadata:
            name: nodeapp1
            labels:
                app: nodeapp1
        spec:
            containers:
            - name: nodeapp1
              image: stepanowon/nodeapp-path1:1.0.0
              ports:
              - containerPort: 8080
            nodeSelector:
                node-group: test1